dubbo:
  application:
    name: elasticsearch-service
    qos-enable: false
  registry:
    address: nacos://localhost:8848
  protocol:
    name: dubbo
    port: 28086
  scan:
    base-packages: org.og.fmall.fmallelasticsearch.services
spring:
  application:
    name: elastic_service
  datasource:
    username: root
    password: fmallstudyououmysql
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 2
    min-idle: 1
    initial-size: 1
    max-wait: 60000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    url: jdbc:mysql://localhost:3306/fmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
elasticsearch:
  host: localhost
  port: 18888
  #是否初始化过了，如果加载过数据库数据到elasticsearch中，true
  hasInitial: true
  #批量插入一次多少数据
  initSize: 10000