
dubbo:
  protocol:
    name: dubbo
  registry:
    address: zookeeper://localhost:2181
  scan: org.og.fmall.fmallorder.iservice.impl
  application:
    name: order-service
  consumer:
    timeout: 6000

spring:
  application:
    name: order_service
  datasource:
    username: yourusername
    password: yourpassword
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    min-idle: 5
    initial-size: 5
    max-wait: 60000
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1 FROM DUAL
    url: jdbc:mysql://localhost:3306/fmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
  banner:
    location: classpath:fmall.txt
server:
  port: 8090

rocketmq:
  namesrvAddr: localhost:9876
  consumer:
    group: OrderConsumer
    reconsumeTimes: 3
  enable: false

rabbitmq:
  host: localhost
  port: 5672
  username: fmalluser
  password: fmall
  enable: true



