
dubbo:
  protocol:
    name: dubbo
  registry:
    address: zookeeper://192.168.12.109:2181
  scan: org.og.fmall.fmallorder.iservice.impl
  application:
    name: order-service
  consumer:
    timeout: 6000

spring:
  application:
    name: order_service
  datasource:
    username: root
    password: mysql123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 10
    min-idle: 1
    initial-size: 1
    max-wait: 60000
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1 FROM DUAL
    url: jdbc:mysql://192.168.12.109:3306/fmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
  banner:
    location: classpath:fmall.txt
server:
  port: 8090
rocketmq:
  namesrvAddr: 192.168.12.109:9876
  consumer:
    group: OrderConsumer
    reconsumeTimes: 3
  enable: false
rabbitmq:
  host: 192.168.12.109
  port: 5672
  username: ougen
  password: zxy
  enable: true

kafka:
  bootstrap-server: 192.168.12.109:9092
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  # 默认发送topic
  topic: order_create
  batch-size: 8192
  # 一秒延迟发送
  linger-ms: 1000
  retries: 2
  buffer-mmory: 16777216
  acks: 0