server:
  port: 18090
dubbo:
  application:
    name: user-service
  protocol:
    port: 20882
    name: dubbo
  registry:
    address: zookeeper://49.235.118.239:2181
  scan:
    base-packages: org.og.fmall.fmalluser.service

spring:
  application:
    name: user_service
  datasource:
    username: yourusername
    password: yourpassword
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
    min-idle: 5
    initial-size: 5
    max-wait: 60000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    url: jdbc:mysql://49.235.118.239:3306/fmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
    filters: stat
  banner:
    location: classpath:fmall.txt