spring:
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 465
    username: 304489914@qq.com
    password: okjrjpgjqvmybjdd
    properties: {mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory, mail.smtp.ssl.enable: true}