
spring:
  profiles:
    active: prod
mybatis:
  type-aliases-package: org.og.fmall.fmallstock.model
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mybatis/mapper/*_mapper.xml
server:
  port: 8081