server:
  port: 18080
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://192.168.12.109:2181
  scan:
    base-packages: org.og.fmall.fmallshop.iservice
  consumer:
    timeout: 6000
  application:
    name: fmall-shop-service
    qos-accept-foreign-ip: false
    qos-enable: false
rocketmq:
  namesrvAddr: 192.168.12.109:9876
  productor:
    group: producter
    reconsumeTimes: 5
  enable: false
error:
  out:
    file: /error.log
spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html
  #    cache: false
  #    servlet:
  #      content-type: text/html
  #    enabled: true
  #    encoding: UTF-8
  #    mode: HTML5
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
  freemarker:
    cache: false
  banner:
    location: classpath:fmall.txt
rabbitmq:
  host: 192.168.12.109
  port: 5672
  username: ougen
  password: zxy
  enable: true
  producer:
    retries: 3
cookie:
  domain: localhost
