
server:
  port: 80
dubbo:
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: nacos://localhost:8848
  scan:
    base-packages: org.og.fmall.fmallshop.iservice
  consumer:
    timeout: 6000
  application:
    name: fmall-shop-service
    qos-accept-foreign-ip: false
    qos-enable: false
rocketmq:
  namesrvAddr: localhost:9876
  productor:
    group: producter
    reconsumeTimes: 5
  enable: false
spring:
  #  thymeleaf:
  #    prefix: classpath:/templates/
  #    suffix: .html
  #    cache: false
  #    servlet:
  #      content-type: text/html
  #    enabled: true
  #    encoding: UTF-8
  #    mode: HTML5
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      enabled: true
      gzipped: true
      html-application-cache: true
    static-locations: classpath:/static/
  freemarker:
    cache: false
  banner:
    location: classpath:fmall.txt
  application:
    name: fmall-shop-service
rabbitmq:
  host: localhost
  port: 5672
  username: username
  password: password
  enable: true
  producer:
    retries: 3
cookie:
  domain: fmall.club
kafka:
  bootstrap-server: localhost:9092
  value-serializer: org.apache.kafka.common.serialization.StringSerializer
  key-serializer: org.apache.kafka.common.serialization.StringSerializer
  # 默认发送topic
  topic: open-log
  batch-size: 8192
  # 一秒延迟发送
  linger-ms: 1000
  retries: 2
  buffer-mmory: 16777216
  acks: 0
pay:
  return:
    url: www.fmall.club:80

soft:
  needTest: true
  time: 60000
mail:
  receiver: email
