dubbo:
  application:
    name: shopping-service
  protocol:
    port: 20885
    name: dubbo
  registry:
    address: zookeeper://localhost:2181
  scan:
    base-packages: org.og.fmall.fmallshopping.service

spring:
  application:
    name: shopping_service
  datasource:
    username: yourusername
    password: yourpassword
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 5
    min-idle: 5
    initial-size: 5
    max-wait: 60000
    test-while-idle: true
    time-between-eviction-runs-millis: 60000
    validation-query: SELECT 1 FROM DUAL
    url: jdbc:mysql://localhost:3306/fmall?useUnicode=true&characterEncoding=utf8&useOldAliasMetadataBehavior=true&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=UTC
  banner:
    location: classpath:fmall.txt
